frontend-ux-wireframe-with-html
intade/6sem-itirod pull request #2
Opened 2021-03-14 18:37 UTC by intade

2021-03-17 15:46 UTC, gmltA requested changes
https://github.com/gmltA/FrontEnd_tasks#acceptance-criteria

I don't think you did what I've expected you to do.

2021-03-23 12:52 UTC, gmltA reviewed
**desktop/2.png** – don't see a reason for multiple `aside`s. The last section should be replaced with `article`.
**desktop/3.png** – can't understand why do you use table here.

It is <kbd>7</kbd> for now. Tell me if you want to improve it.

2021-03-23 13:21 UTC, intade commented
i'm okay with 7

2021-03-23 13:53 UTC, gmltA approved these changes

2021-03-31 15:09 UTC, merged